Small refactor

diff --git a/music-dl b/music-dl
--- a/music-dl
+++ b/music-dl
@@ -5,45 +5,59 @@
 # License:    MIT, https://opensource.org/licenses/MIT
 
 set -eu
+export LC_ALL=C
 
-printAction() {
-	printf -- '\033[1;33m + \033[1;32m%s \033[0m\n' "$@"
+printInfo() { [ -t 1 ] && printf -- '\033[0m[\033[1;32mINFO\033[0m] %s\n' "$@" || printf -- '[INFO] %s\n' "$@"; }
+printWarn() { [ -t 1 ] && printf -- '\033[0m[\033[1;33mWARN\033[0m] %s\n' "$@" >&2 || printf -- '[WARN] %s\n' "$@" >&2; }
+printError() { [ -t 1 ] && printf -- '\033[0m[\033[1;31mERROR\033[0m] %s\n' "$@" >&2 || printf -- '[ERROR] %s\n' "$@" >&2; }
+
+main() {
+	OUT_DIR=${DESTDIR:-${HOME:?}/Downloads/}
+	mkdir -p "${OUT_DIR:?}"
+
+	TMP_DIR=$(mktemp -dt music-dl.XXXXXXXX)
+	trap 'rm -rf "${TMP_DIR:?}"; trap - EXIT; exit 0' EXIT TERM INT HUP
+
+	printInfo 'Downloading files...'
+	if command -v youtube-dl >/dev/null; then
+		youtube-dl \
+			--no-continue \
+			--format 'bestaudio' \
+			--output "${TMP_DIR:?}/%(title)s.%(ext)s" \
+			--default-search 'ytsearch' \
+			-- "$@"
+	else
+		printError 'youtube-dl is required for this step'
+		exit 1
+	fi
+
+	printInfo 'Encoding files to VBR MP3 and trimming silence...'
+	if command -v ffmpeg >/dev/null; then
+		for inFile in "${TMP_DIR:?}"/*; do
+			outFile=${inFile%.*}.mp3
+			tmpFile=$(mktemp -ut .XXXXXXXX.mp3 -p "${TMP_DIR:?}")
+			silenceremove='start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak'
+			filters="silenceremove=${silenceremove:?},aformat=dblp,areverse,silenceremove=${silenceremove:?},aformat=dblp,areverse"
+			ffmpeg -hide_banner -i "${inFile:?}" -codec:a libmp3lame -qscale:a 2 -af "${filters:?}" "${tmpFile:?}"
+			rm -f "${inFile:?}"; mv -f "${tmpFile:?}" "${outFile:?}"
+		done
+	else
+		printWarn 'ffmpeg is required for this step'
+	fi
+
+	printInfo 'Cleaning metadata...'
+	if command -v mat2 >/dev/null; then
+		find "${TMP_DIR:?}" -type f -name '*.mp3' -exec mat2 --inplace '{}' ';'
+	elif command -v id3convert >/dev/null; then
+		find "${TMP_DIR:?}" -type f -name '*.mp3' -exec id3convert --strip '{}' ';'
+	elif command -v eyeD3 >/dev/null; then
+		find "${TMP_DIR:?}" -type f -name '*.mp3' -exec eyeD3 --remove-all '{}' ';'
+	else
+		printWarn 'mat2, id3convert or eyeD3 are required for this step'
+	fi
+
+	printInfo 'Moving files to output directory...'
+	find "${TMP_DIR:?}" -type f -name '*.mp3' -exec mv -f '{}' "${OUT_DIR:?}"/ ';'
 }
 
-OUT_DIR=${HOME}/Downloads/music-dl
-mkdir -p "${OUT_DIR}"
-
-TMP_DIR=$(mktemp -dt music-dl.XXXXXXXX)
-trap 'rm -rf ${TMP_DIR:?}' EXIT
-
-printAction 'Downloading files...'
-youtube-dl \
-	--no-continue \
-	--format 'bestaudio' \
-	--output "${TMP_DIR}/%(title)s.%(ext)s" \
-	--default-search 'ytsearch' \
-	-- "$@"
-
-printAction 'Encoding files to VBR MP3 and trimming silence...'
-for file in "${TMP_DIR}"/*; do
-	outFile=${file%.*}.mp3
-	tmpFile=$(mktemp -ut .XXXXXXXX.mp3 -p "${TMP_DIR}")
-	silenceremove='start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak'
-	filters="silenceremove=${silenceremove},aformat=dblp,areverse,silenceremove=${silenceremove},aformat=dblp,areverse"
-	ffmpeg -hide_banner -i "${file}" -codec:a libmp3lame -qscale:a 2 -af "${filters}" "${tmpFile}"
-	rm -f "${file}"; mv -f "${tmpFile}" "${outFile}"
-done
-
-if command -v eyeD3 >/dev/null; then
-	printAction 'Cleaning metadata using eyeD3...'
-	find "${TMP_DIR}" -type f -name '*.mp3' -exec eyeD3 --remove-all '{}' ';'
-elif command -v id3convert >/dev/null; then
-	printAction 'Cleaning metadata using id3lib...'
-	find "${TMP_DIR}" -type f -name '*.mp3' -exec id3convert --strip '{}' ';'
-elif command -v mat >/dev/null; then
-	printAction 'Cleaning metadata using MAT...'
-	find "${TMP_DIR}" -type f -name '*.mp3' -exec mat '{}' ';'
-fi
-
-printAction 'Moving files to output directory...'
-find "${TMP_DIR}" -type f -name '*.mp3' -exec mv -f '{}' "${OUT_DIR}"/ ';'
+main "$@"
